# Generated by Django 5.2 on 2025-05-13 11:20

from django.db import migrations

from django.db import migrations
import re

def migrate_experience(apps, schema_editor):
    Job = apps.get_model('jobs', 'Job')

    for job in Job.objects.all():
        exp = job.experience_required
        match = re.match(r'(\d+)\s*-\s*(\d+)', exp)
        if match:
            job.min_experience = int(match.group(1))
            job.max_experience = int(match.group(2))
            job.save()

class Migration(migrations.Migration):

    dependencies = [
       ('jobs', '0002_job_max_experience_job_min_experience'),
    ]

    operations = [
        migrations.RunPython(migrate_experience),
    ]