# Generated by Django 5.2 on 2025-05-13 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20250513_1120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='experience_required',
        ),
    ]
