version: '3.9'

services:
  web:
    build: .
    command: ["./wait-for-db.sh", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=True
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=Job_Board_CustomUser
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: Job_Board_CustomUser
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

  redis:
    image: redis:alpine
  
  celery:
    build: .
    command: celery -A job_board worker --loglevel=info
    depends_on:
      - web
      - redis
    volumes:
      - .:/app
    environment:
      - DEBUG= 1
      - CELERY_BROKER_URL=redis://redis:6379/0

volumes:
  postgres_data: