# Generated by Django 5.2 on 2025-05-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobseekerprofile',
            old_name='user',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='recruiterprofile',
            old_name='user',
            new_name='profile',
        ),
    ]
